// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function GetAbility(arg1:string):Promise<core.Ability>;

export function GetEvolutionChain(arg1:number):Promise<core.EvolutionChain>;

export function GetMove(arg1:string):Promise<core.Move>;

export function GetPokemon(arg1:string):Promise<core.Pokemon>;

export function GetRegion(arg1:string):Promise<core.Region>;

export function GetType(arg1:string):Promise<core.PokemonTypeDetail>;

export function ListPokemon(arg1:number,arg2:number):Promise<core.PokemonListResponse>;

export function ListRegions():Promise<Array<core.Region>>;

export function ListTypes():Promise<core.TypeListResponse>;
