// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateEVs(arg1) {
  return window['go']['app']['App']['CalculateEVs'](arg1);
}

export function CalculateStats(arg1) {
  return window['go']['app']['App']['CalculateStats'](arg1);
}

export function CreateTeam(arg1) {
  return window['go']['app']['App']['CreateTeam'](arg1);
}

export function DeleteTeam(arg1) {
  return window['go']['app']['App']['DeleteTeam'](arg1);
}

export function DeleteTeamMember(arg1, arg2) {
  return window['go']['app']['App']['DeleteTeamMember'](arg1, arg2);
}

export function DownloadSprites(arg1) {
  return window['go']['app']['App']['DownloadSprites'](arg1);
}

export function ExecuteTurn(arg1) {
  return window['go']['app']['App']['ExecuteTurn'](arg1);
}

export function GetAbility(arg1) {
  return window['go']['app']['App']['GetAbility'](arg1);
}

export function GetAllAbilities() {
  return window['go']['app']['App']['GetAllAbilities']();
}

export function GetAllMoves() {
  return window['go']['app']['App']['GetAllMoves']();
}

export function GetEggGroup(arg1) {
  return window['go']['app']['App']['GetEggGroup'](arg1);
}

export function GetEvolutionChain(arg1) {
  return window['go']['app']['App']['GetEvolutionChain'](arg1);
}

export function GetGender(arg1) {
  return window['go']['app']['App']['GetGender'](arg1);
}

export function GetGeneration(arg1) {
  return window['go']['app']['App']['GetGeneration'](arg1);
}

export function GetGrowthRate(arg1) {
  return window['go']['app']['App']['GetGrowthRate'](arg1);
}

export function GetLocation(arg1) {
  return window['go']['app']['App']['GetLocation'](arg1);
}

export function GetLocationArea(arg1) {
  return window['go']['app']['App']['GetLocationArea'](arg1);
}

export function GetMachine(arg1) {
  return window['go']['app']['App']['GetMachine'](arg1);
}

export function GetMove(arg1) {
  return window['go']['app']['App']['GetMove'](arg1);
}

export function GetMoveAilment(arg1) {
  return window['go']['app']['App']['GetMoveAilment'](arg1);
}

export function GetMoveDamageClass(arg1) {
  return window['go']['app']['App']['GetMoveDamageClass'](arg1);
}

export function GetMoveTarget(arg1) {
  return window['go']['app']['App']['GetMoveTarget'](arg1);
}

export function GetNatureDetail(arg1) {
  return window['go']['app']['App']['GetNatureDetail'](arg1);
}

export function GetNatures() {
  return window['go']['app']['App']['GetNatures']();
}

export function GetPokedex(arg1) {
  return window['go']['app']['App']['GetPokedex'](arg1);
}

export function GetPokemon(arg1) {
  return window['go']['app']['App']['GetPokemon'](arg1);
}

export function GetPokemonForm(arg1) {
  return window['go']['app']['App']['GetPokemonForm'](arg1);
}

export function GetPokemonSpecies(arg1) {
  return window['go']['app']['App']['GetPokemonSpecies'](arg1);
}

export function GetRegion(arg1) {
  return window['go']['app']['App']['GetRegion'](arg1);
}

export function GetRegionPokemonByType(arg1, arg2) {
  return window['go']['app']['App']['GetRegionPokemonByType'](arg1, arg2);
}

export function GetStatDetail(arg1) {
  return window['go']['app']['App']['GetStatDetail'](arg1);
}

export function GetTeam(arg1) {
  return window['go']['app']['App']['GetTeam'](arg1);
}

export function GetType(arg1) {
  return window['go']['app']['App']['GetType'](arg1);
}

export function GetVersionGroup(arg1) {
  return window['go']['app']['App']['GetVersionGroup'](arg1);
}

export function InitBattle(arg1, arg2) {
  return window['go']['app']['App']['InitBattle'](arg1, arg2);
}

export function ListAbilities(arg1, arg2) {
  return window['go']['app']['App']['ListAbilities'](arg1, arg2);
}

export function ListGenerations() {
  return window['go']['app']['App']['ListGenerations']();
}

export function ListMoves(arg1, arg2) {
  return window['go']['app']['App']['ListMoves'](arg1, arg2);
}

export function ListNatureNames() {
  return window['go']['app']['App']['ListNatureNames']();
}

export function ListPokedexes() {
  return window['go']['app']['App']['ListPokedexes']();
}

export function ListPokemon(arg1, arg2) {
  return window['go']['app']['App']['ListPokemon'](arg1, arg2);
}

export function ListPokemonColors() {
  return window['go']['app']['App']['ListPokemonColors']();
}

export function ListPokemonHabitats() {
  return window['go']['app']['App']['ListPokemonHabitats']();
}

export function ListPokemonShapes() {
  return window['go']['app']['App']['ListPokemonShapes']();
}

export function ListRegions() {
  return window['go']['app']['App']['ListRegions']();
}

export function ListTeams() {
  return window['go']['app']['App']['ListTeams']();
}

export function ListTypes() {
  return window['go']['app']['App']['ListTypes']();
}

export function ListVersionGroups() {
  return window['go']['app']['App']['ListVersionGroups']();
}

export function SaveToTeam(arg1, arg2) {
  return window['go']['app']['App']['SaveToTeam'](arg1, arg2);
}

export function ScrapePokedex() {
  return window['go']['app']['App']['ScrapePokedex']();
}

export function SimulateDamage(arg1) {
  return window['go']['app']['App']['SimulateDamage'](arg1);
}

export function SimulateFullBattle(arg1) {
  return window['go']['app']['App']['SimulateFullBattle'](arg1);
}

export function SimulateMultipleBattles(arg1, arg2) {
  return window['go']['app']['App']['SimulateMultipleBattles'](arg1, arg2);
}
