// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPokemon(arg1) {
  return window['go']['app']['App']['GetPokemon'](arg1);
}

export function ListPokemon(arg1, arg2) {
  return window['go']['app']['App']['ListPokemon'](arg1, arg2);
}
