// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function GetPokemon(arg1:string):Promise<core.Pokemon>;

export function GetType(arg1:string):Promise<core.PokemonTypeDetail>;

export function ListPokemon(arg1:number,arg2:number):Promise<core.PokemonListResponse>;

export function ListTypes():Promise<core.TypeListResponse>;
