// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function CalculateEVs(arg1:core.EVCalculatorInput):Promise<core.EVCalculatorResult>;

export function CalculateStats(arg1:core.StatCalculatorInput):Promise<core.Stats>;

export function GetNatures():Promise<Array<core.Nature>>;

export function GetPokemon(arg1:string):Promise<core.Pokemon>;

export function ListPokemon(arg1:number,arg2:number):Promise<core.PokemonListResponse>;
